version: "3"

services:

  appdb:
    image: postgres:9.6
    command: -p $DB_PORT
    ports:
      - "$DB_PORT:$DB_PORT"
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE_NAME
    networks:
      - brain-network
  
  discovery:
    image: consul:1.6
    ports:
      - "8500:8500"
    networks:
      - brain-network
    environment:
      CONSUL_BIND_INTERFACE: "eth0"

  frontend:
    build:
      context: brain-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - brain-network
    depends_on:
      - "auth-service"
  
  auth-service:
    build:
      context: auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - brain-network
    depends_on:
      - "appdb"
      - "discovery"
    environment:
      SKIP_VAULT: "true"
      DB_DATABASE_NAME: $DB_DATABASE_NAME
      DB_HOST: appdb
      DB_PORT: $DB_PORT
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      DISCOVERY_URL: discovery:8500
      DISCOVERY_TOKEN: $DISCOVERY_TOKEN
      ENABLE_DB: "true"
      FRONTEND_URL: frontend:4200
      OAUTH2_GOOGLE_CLIENT_ID: $OAUTH2_GOOGLE_CLIENT_ID
      OAUTH2_GOOGLE_CLIENT_SECRET: $OAUTH2_GOOGLE_CLIENT_SECRET
      OAUTH2_GOOGLE_REDIRECT_URL: $OAUTH2_GOOGLE_REDIRECT_URL
      OAUTH2_GOOGLE_USER_EMAIL_SCOPE: $OAUTH2_GOOGLE_USER_EMAIL_SCOPE
      OAUTH2_GOOGLE_USER_INFO_EMAIL: $OAUTH2_GOOGLE_USER_INFO_EMAIL
      OAUTH2_GOOGLE_USER_INFO_NAME: $OAUTH2_GOOGLE_USER_INFO_NAME
      OAUTH2_GOOGLE_USER_INFO_PICTURE: $OAUTH2_GOOGLE_USER_INFO_PICTURE
      OAUTH2_GOOGLE_USER_INFO_URL: $OAUTH2_GOOGLE_USER_INFO_URL
      OAUTH2_GOOGLE_USER_PROFILE_SCOPE: $OAUTH2_GOOGLE_USER_PROFILE_SCOPE
      PORT: "8080"

networks:
  brain-network:
    driver: bridge
