version: "3"

services:
  appdb:
    image: postgres:9.6
    command: -p $DB_PORT
    ports:
      - "$DB_PORT:$DB_PORT"
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE_NAME
    networks:
      - brain-network

  discovery:
    image: consul:1.6
    ports:
      - "8500:8500"
    networks:
      - brain-network
    environment:
      CONSUL_BIND_INTERFACE: "eth0"

  frontend:
    build:
      context: repos
      dockerfile: brain-frontend/Dockerfile
    ports:
      - "4200:4200"
    networks:
      - brain-network
    depends_on:
      - "auth-service"

  auth-service:
    build:
      context: repos
      dockerfile: auth-service/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - brain-network
    depends_on:
      - "appdb"
      - "discovery"
    environment:
      SKIP_VAULT: "true"
      DB_DATABASE_NAME: $DB_DATABASE_NAME
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      DISCOVERY_URL: discovery:8500
      DISCOVERY_TOKEN: $DISCOVERY_TOKEN
      ENABLE_DB: "true"
      FRONTEND_URL: 127.0.0.1:4200
      OAUTH2_GOOGLE_CLIENT_ID: $OAUTH2_GOOGLE_CLIENT_ID
      OAUTH2_GOOGLE_CLIENT_SECRET: $OAUTH2_GOOGLE_CLIENT_SECRET
      OAUTH2_GOOGLE_REDIRECT_URL: $OAUTH2_GOOGLE_REDIRECT_URL
      OAUTH2_GOOGLE_USER_EMAIL_SCOPE: $OAUTH2_GOOGLE_USER_EMAIL_SCOPE
      OAUTH2_GOOGLE_USER_INFO_EMAIL: $OAUTH2_GOOGLE_USER_INFO_EMAIL
      OAUTH2_GOOGLE_USER_INFO_NAME: $OAUTH2_GOOGLE_USER_INFO_NAME
      OAUTH2_GOOGLE_USER_INFO_PICTURE: $OAUTH2_GOOGLE_USER_INFO_PICTURE
      OAUTH2_GOOGLE_USER_INFO_URL: $OAUTH2_GOOGLE_USER_INFO_URL
      OAUTH2_GOOGLE_USER_PROFILE_SCOPE: $OAUTH2_GOOGLE_USER_PROFILE_SCOPE
      PORT: "8080"
      RPC_PORT: "9090"
      OAUTH2_GOOGLE_USER_INFO_TIMEOUT: $OAUTH2_GOOGLE_USER_INFO_TIMEOUT
      RESPONSE_TIMEOUT: $RESPONSE_TIMEOUT
      SERVICE_DOMAIN: "auth-service"
      IS_AUTH_SERVICE: "true"

  file-uploader-service:
    build:
      context: repos
      dockerfile: file-uploader-service/Dockerfile
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - brain-network
    depends_on:
      - "appdb"
      - "discovery"
      - "auth-service"
    environment:
      SKIP_VAULT: "true"
      DB_DATABASE_NAME: $DB_DATABASE_NAME
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      DISCOVERY_URL: discovery:8500
      DISCOVERY_TOKEN: $DISCOVERY_TOKEN
      ENABLE_DB: "true"
      PORT: "8081"
      RPC_PORT: "8082"
      SERVICE_DOMAIN: "file-uploader-service"
      FILE_UPLOADER_PRIVATE_KEY: $FILE_UPLOADER_PRIVATE_KEY
      FILE_UPLOADER_PUBLIC_KEY: $FILE_UPLOADER_PUBLIC_KEY

  data-integration-service:
    build:
      context: repos
      dockerfile: data-integration-service/Dockerfile
    ports:
      - "8090:8090"
      - "8091:8091"
    networks:
      - brain-network
    depends_on:
      - "appdb"
      - "discovery"
      - "auth-service"
    environment:
      SKIP_VAULT: "true"
      DB_DATABASE_NAME: $DB_DATABASE_NAME
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      DISCOVERY_URL: discovery:8500
      DISCOVERY_TOKEN: $DISCOVERY_TOKEN
      ENABLE_DB: "true"
      PORT: "8090"
      RPC_PORT: "8091"
      SERVICE_DOMAIN: "data-integration-service"

  octopus-service:
    build:
      context: repos
      dockerfile: octopus-service/Dockerfile
    ports:
      - "8087:8087"
      - "8088:8088"
    networks:
      - brain-network
    depends_on:
      - "appdb"
      - "discovery"
      - "auth-service"
    environment:
      SKIP_VAULT: "true"
      DB_DATABASE_NAME: $DB_DATABASE_NAME
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      DISCOVERY_URL: discovery:8500
      DISCOVERY_TOKEN: $DISCOVERY_TOKEN
      ENABLE_DB: "true"
      PORT: "8087"
      RPC_PORT: "8088"
      SERVICE_DOMAIN: "octopus-service"
      DUCKLING_SERVER: "http://duckling.cuttle.ai:8000"

networks:
  brain-network:
    driver: bridge
